# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod Information
mod_id=villagecraft3essentials
mod_name=VillageCraft 3 Essentials
mod_license=MIT
mod_version=1.21.1alpha-v1.0.24
mod_group_id=com.timeshipmodding.villagecraft3essentials
mod_credits=Created by Timeship Modding. Kaupenjoe's Courses/Tutorials and Google Gemini generated code used as reference.
mod_authors=TardisEngineer
mod_description=VillageCraft 3 Essentials is a mod built for the VillageCraft 3 Modpack which is used on the private SMP, VillageCraft 3. This mod adds custom ores to use as currency, which are copies of diamonds in every way. The other feature added is the ATM, a block which allows you to exchange currencies into another currency with random exchange rates. This mod also includes several other utility features for the SMP.

# Minecraft Versions
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge Versions
neo_version=21.1.224
neo_version_range=[21.1.0,)
loader_version_range=[1,)

# Parchment Versions
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# JEI Versions
jei_version=19.27.0.336
mc_version=1.21.1

# Aquaculture 2 Version
aquaculture_version = 2.7.21