# Mod Loading Info
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

# VillageCraft 3 Essentials Conifg
[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''

# Access Transformer
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

# Mixins
[[mixins]]
    config="${mod_id}.mixins.json"

# Dependency for Minecraft
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Dependency for NeoForge
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

# Dependency for JEI
[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[19.27.0.336,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Luckperms
[[dependencies.${mod_id}]]
    modId="luckperms"
    type="optional"
    versionRange="[5.4.140,)"
    ordering="AFTER"
    side="SERVER"

# Dependency for Farmer's Delight
[[dependencies.${mod_id}]]
    modId="farmersdelight"
    type="optional"
    versionRange="[1.2.11a,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Aquaculture 2
[[dependencies.${mod_id}]]
    modId="aquaculture"
    type="optional"
    versionRange="[2.7.21,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Better Archeology
[[dependencies.${mod_id}]]
    modId="betterarcheology"
    type="optional"
    versionRange="[1.3.4,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Create
[[dependencies.${mod_id}]]
    modId="create"
    type="optional"
    versionRange="[6.0.10,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Discord Integration
[[dependencies.${mod_id}]]
    modId="dcintegration"
    type="optional"
    versionRange="[3.0.7,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Create: Brassworks Missions
[[dependencies.${mod_id}]]
    modId="brassworksmissions"
    type="optional"
    versionRange="[1.13,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Simple Guns Reworked
[[dependencies.${mod_id}]]
    modId="simple_guns_reworked"
    type="optional"
    versionRange="[1.9.0,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Archers (RPG Series Plus)
[[dependencies.${mod_id}]]
    modId="elemental_wizards_rpg"
    type="optional"
    versionRange="[2.6.7,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Elemental Wizards (RPG Series)
[[dependencies.${mod_id}]]
    modId="archers"
    type="optional"
    versionRange="[2.7.0,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Armory (RPG Series Plus)
[[dependencies.${mod_id}]]
    modId="elemental_wizards_rpg"
    type="optional"
    versionRange="[1.3.0,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Create Goggles
[[dependencies.${mod_id}]]
    modId="creategoggles"
    type="optional"
    versionRange="[6.1.1,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Enderscape
[[dependencies.${mod_id}]]
    modId="enderscape"
    type="optional"
    versionRange="[1.0.9,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Galosphere
[[dependencies.${mod_id}]]
    modId="galosphere"
    type="optional"
    versionRange="[1.5.5,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Supplementaries
[[dependencies.${mod_id}]]
    modId="supplementaries"
    type="optional"
    versionRange="[1.21.1-3.6.8,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Yung's Cave Biomes
[[dependencies.${mod_id}]]
    modId="yungscavebiomes"
    type="optional"
    versionRange="[1.21.1-NeoForge-3.1.1,)"
    ordering="AFTER"
    side="BOTH"

# Dependency for Bluemap
[[dependencies.${mod_id}]]
    modId="bluemap"
    type="optional"
    versionRange="[5.7,)"
    ordering="AFTER"
    side="BOTH"